### ISSUE TITLE
Englisch vs. Deutsch

### ISSUE THREAD

**Issue by DominicFrei** [DominicFrei/the-swift-programming-language-in-german#4]
Aktuell sind Teile der Dokumentation in diesem Github-Repo noch in English. So etwa die Dateinamen der Kapitel und Sektionen. Darin enthalten sind deutsche Texte, die wiederum Englische Keywords enthalten.

Ich bin mir an manchen Stellen nicht so 100% sicher, wie und wo man sinnvollerweise den Cut macht, vor allem da unsere Sprache ja doch recht voll mit Denglisch ist.

Die Dateinamen habe ich damals Englisch gewaehlt, da sie damit die Verbindung zu den Kapiteln aus der Original-Dokumentation darstellen.

@mauruskuehne Meinungen, wo wir das am sinnvollsten trennen sollten? :)

**Comment by mauruskuehne** [comment]
Die Frage habe ich mir die letzten paar Tage auch schon öfters gestellt ;)
Ich denke die Dateinamen können wir auf Englisch lassen. So haben wir wie du sagst gleich die Verknüpfung zum englischen Original. Zudem scheint das für unsere chinesischen Kollegen ja auch gut zu funktionieren :)

Beim Text selbst bin ich mir ehrlich gesagt auch nicht ganz sicher, wie weit wir alles übersetzen sollen. Ich habe aber mal einige meiner Informatik-Lehrbücher durchgeblättert. Da ist meistens alles (inkl. der Fachbegriffe) übersetzt, auch wenn dabei teilweise etwas komische Bezeichnungen entstehen (z.B. "sondierende Methoden" oder "Abkürzungsoperatoren"). Nur sehr weit verbreitete Begriffe wie z.B. "Client" oder "Server" sind darin nicht übersetzt.
In der MSDN wird in der C# Sprachreferenz auch fast alles übersetzt. Es gibt nur einige wenige Ausnahmen (z.B. "Accessor" als Bezeichnung für Getter und Setter eines Properties).

Ich wäre deshalb dafür, dass wir das ähnlich machen. Also wenn möglich alle Begriffe (auch Fachbegriffe wie z.B. "Optionals") übersetzen. Nur in Fällen wo keine sinnvolle Übersetzung möglich ist, sollten wir auf einen englischen Begriff zurückgreifen. 

Ich denke, das macht die Doku dann auch einfacher für komplette Programmieranfänger. 

Wie siehst du das? :)

**Comment by DominicFrei** [comment]
Ja, das stimmt schon. Wobei ich in den Buechern die Uebersetzungen meist zum Lachen finde. :D 
Kommt vielleicht aber auch daher, dass ich eben Englisch kann und die Uebersetzung kenne und dann halt den Zusammenhang manchmal nicht sehe, wenn jemand mal wieder willkuerlich uebersetzt hat.

Das naechste ist ja, wenn jemand dann doch mal in einem englischen Text oder Forum oder stackoverflow oder sowas liest und mit seinem halben Englisch dann versucht, das zu verstehen, waere es natuerlich hilfreich, die englischen Originale zu kennen.

Da stellt sich also die Frage, wie ist es um das Englisch unserer Kollegen bestellt, die diese deutsche Version der Swift-Doku lesen werden / wuerden.

Eine weitere Variante koennte ja sein, beim ersten Auftreten (oder allgemein?) den englischen Begriff noch mit zu nennen..
Auch da bin ich mir unsicher, ob das zielfuehrend ist ..

Auf alle Faelle sinnvoll wird es aber wohl sein, wie du ja auch schon dargestellt hast, die Dateinahmen in Englisch zu belassen.

Und was machen wir nun? :D

**Comment by mauruskuehne** [comment]
Haha, ja die Übersetzungen in den Büchern sind teilweise echt schlimm :smile: 
Den englischen Begriff jeweils direkt dazu zu schreiben gefällt mir sehr. Ich würde sie aber nur bei der ersten Beschreibung eines Begriffs hinzufügen, nicht bei jedem Vorkommen. Bei Sätzen mit vielen Fachwörtern wirds sonst unübersichtlich :sweat_smile: 
Stattdessen könnten wir die Begriffe auch einfach verlinken, damit man an die zugehörige Stelle in der Doku kommt. Da wäre wiederum der englische Begriff beschrieben.

Wir könnten es auch mit einem Glossar lösen. Ich stelle mir sowas in der Art vor:

| Begriff (de) | Begriff (en) | Beschreibung |
|----------------|-----------------|--------------------|
| Ganzzahl ([Link auf unsere Doku](blabla)) | Integer ([Link auf Apple Doku](blabla)) | Eine Zahl ohne Bruchanteil |

Mir würde folgende Lösung gut gefallen:

* Englische Bezeichnungen bei der ersten Beschreibung hinzufügen
* Alle weiteren Verwendungen der deutschen Bezeichnung mit deren Beschreibung verlinken
* Optional: Glossar über alle Fachwörter damit wir sie überall gleich nennen

Anstelle eines "öffentlichen" Glossars wäre aber so oder so ein internes Glossar hilfreich, damit die Fachwörter sicher immer gleich übersetzt werden. 

Was unsere Zielgruppe angeht: Ich denke wir sollten uns eher an Leute richten, die nicht so gut Englisch verstehen. Wenn sie englisch verstehen würden, würden sie ziemlich sicher die Originaldoku lesen. Diese wird sicher aktueller / exakter sein. So sehe ich das zumindest :)

**Comment by DominicFrei** [comment]
Das gefaellt mir! :)

Dann lass uns doch direkt die Variante 'offener Glossar' waehlen, dann haben beide Seiten etwas davon. Dahin verlinken wir alle Worte, die im Text irgendwie vor kommen und vom Glossar gibt's dann - wie in einem Glossar in einem Buch eben - einen Link auf die Stelle, an der das Wort erstmalig auftrat (und auch erklaert wird).

Wahrscheinlich muessen wir dann am Ende noch mal ueber alles drueber gehen und checken, ob das auch passt ... :D 

Magst du deine Ausfuehrungen auch wieder in den Bereich 'Contributing' packen, damit sie weitere Contributer kennen bzw. wir fuer uns wissen, was wir festgelegt haben? :)

**Comment by mauruskuehne** [comment]
jepp, werde ich machen! Hast du eine Idee, wie wir am besten die Links definieren? 
Die chinesische Übersetzung macht aus den Markdown Files am Schluss eine Webseite: [chin. Handbuch](http://wiki.jikexueyuan.com/project/swift/chapter2/01_The_Basics.html)

Habe aber ehrlich gesagt keine Ahnung, wie die das machen :(

**Comment by mauruskuehne** [comment]
Die chinesische Übersetzung scheint es übrigens ähnlich zu machen, die haben auch jeweils die englische Bezeichnung im Titel (zumindest bei den einzelnen Sektionen).

**Comment by DominicFrei** [comment]
Also ich verstehe nur chinesisch. :D

Ja, Links in Markdown, da muss ich mich auch noch ein wenig einlesen. Erst mal wuerde ja ein Link auf die 'Seite' reichen oder?
Also wie in der [Readme](https://github.com/DominicFrei/the-swift-programming-language-in-german).
Wie man das spaeter dann als Webseite oder Buch macht, koennen wir uns ja dann noch ueberlegen. Erst mal mit Inhalt fuellen. ;) Das habe ich fuer diese Woche auch auf der TODO-Liste, jetzt da ja die Feiertage endlich rum sind und wieder Zeit ist, sinnvolles zu tun. :)

**Comment by mauruskuehne** [comment]
Ja, ist in Ordnung für mich :) 
Also wenn wir z.B. [hier](https://github.com/mauruskuehne/the-swift-programming-language-in-german/blob/die-grundlagen/source/chapter2_language_guide/01_the_basics.md) auf das Kapitel "Typhinweise (Type Annotations)" verweisen möchten, würden wir einfach einen Link auf "Die Grundlagen" machen?

**Comment by DominicFrei** [comment]
Ach jetzt daemmert mir auch mal, was du meinst. 

HTML-Anchor funktionieren wohl auch in Markdown:
http://blog.justin.kelly.org.au/anchor-links-in-markdown/

Meinst du das? Oder bin ich nach wie vor auf dem falschen Dampfer? :D

**Comment by mauruskuehne** [comment]
aaah das klingt super :D Ja ich denke das beantwortet meine Frage. Die Links machen wir vorerst einfach direkt auf dein Repo (also https://github.com/DominicFrei/.../)? Wenn wir irgendwann eine Webseite daraus machen, können wir die Links ja schnell austauschen.

**Comment by DominicFrei** [comment]
@mauruskuehne Ja, die Idee finde ich super! :)
